#!/usr/bin/env node
import { pathToFileURL } from "node:url";
export const DEFAULT_MAX_RESPONSE_BYTES = 4 * 1024 * 1024;
const MAX_ACTION_INPUT_BYTES = 64 * 1024;
export class GatewayRequestError extends Error { constructor(message,{status}={}) { super(message); this.name="GatewayRequestError"; this.status=status; } }
function requiredEnv(env,name) { const value=env[name]?.trim(); if(!value) throw new TypeError(`${name} is required`); return value; }
function normalizeGatewayUrl(value) { let url; try { url=new URL(value); } catch { throw new TypeError("HERMES_GATEWAY_URL must be a valid URL"); } const local=["localhost","127.0.0.1","::1"].includes(url.hostname)&&url.protocol==="http:"; if(url.protocol!=="https:"&&!local) throw new TypeError("HERMES_GATEWAY_URL must use HTTPS"); if(url.username||url.password||url.search||url.hash) throw new TypeError("HERMES_GATEWAY_URL must not contain credentials or parameters"); return url.toString().replace(/\/$/,""); }
export function loadWorkerConfig(env=process.env) { return {gatewayUrl:normalizeGatewayUrl(requiredEnv(env,"HERMES_GATEWAY_URL")),internalToken:requiredEnv(env,"HERMES_GATEWAY_INTERNAL_TOKEN")}; }
async function readBoundedJson(response,maxBytes) { const reader=response.body?.getReader(); const chunks=[]; let total=0; while(reader) { const {done,value}=await reader.read(); if(done) break; total+=value.byteLength; if(total>maxBytes) { await reader.cancel(); throw new GatewayRequestError(`Gateway response exceeds ${maxBytes} bytes`,{status:response.status}); } chunks.push(Buffer.from(value)); } try { return JSON.parse(Buffer.concat(chunks).toString("utf8")); } catch { throw new GatewayRequestError("Gateway returned invalid JSON",{status:response.status}); } }
export async function performMeshAction({gatewayUrl,internalToken,action,fetchImpl=globalThis.fetch,maxResponseBytes=DEFAULT_MAX_RESPONSE_BYTES}) { if(!action||typeof action!=="object"||Array.isArray(action)) throw new TypeError("action must be an object"); const response=await fetchImpl(new Request(new URL("/internal/mesh/actions",`${normalizeGatewayUrl(gatewayUrl)}/`),{method:"POST",headers:{authorization:`Bearer ${internalToken}`,"content-type":"application/json"},body:JSON.stringify(action)})); const parsed=await readBoundedJson(response,maxResponseBytes); if(!response.ok) throw new GatewayRequestError(`Gateway request failed with status ${response.status}`,{status:response.status}); return parsed; }
async function readStdinBounded(stream=process.stdin) { const chunks=[]; let total=0; for await(const chunk of stream) { total+=chunk.byteLength; if(total>MAX_ACTION_INPUT_BYTES) throw new TypeError(`Action input exceeds ${MAX_ACTION_INPUT_BYTES} bytes`); chunks.push(Buffer.from(chunk)); } return Buffer.concat(chunks).toString("utf8"); }
function usage() { return "Usage:\n  hermes-a2a mesh-publish\n  hermes-a2a mesh-reply --post-id <id>\n  hermes-a2a mesh-claim --post-id <id>\n"; }
export async function main(argv=process.argv.slice(2),io={stdout:process.stdout,stderr:process.stderr,readStdin:()=>readStdinBounded()},{env=process.env,fetchImpl=globalThis.fetch}={}) { const command=argv[0]==="mesh-publish"&&argv.length===1?{operation:"posts.publish"}:argv[0]==="mesh-reply"&&argv.length===3&&argv[1]==="--post-id"&&argv[2]?{operation:"posts.reply",post_id:argv[2]}:argv[0]==="mesh-claim"&&argv.length===3&&argv[1]==="--post-id"&&argv[2]?{operation:"tasks.claim",post_id:argv[2]}:null; if(!command){io.stderr.write(usage());return 2;} try { const text=(await io.readStdin()).trim(); let input; try { input=JSON.parse(text); } catch { throw new TypeError("Action input must be valid JSON"); } if(!input||typeof input!=="object"||Array.isArray(input)) throw new TypeError("Action input must be a JSON object"); const result=await performMeshAction({...loadWorkerConfig(env),fetchImpl,action:{...input,...command}}); io.stdout.write(`${JSON.stringify(result)}\n`); return 0; } catch(error) { io.stderr.write(`${error instanceof GatewayRequestError?`Gateway request failed${error.status?` (${error.status})`:""}`:error?.message||"Worker failed"}\n`); return 1; } }
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href) process.exitCode=await main();
